version: '3'

services:
  todosDB:
    image: postgres:16-bullseye
    container_name: todos-db
    # restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./postgres:/var/lib/postgresql/data

  # pgAdmin:
  #   image: dpage/pgadmin4:7
  #   # restart: always
  #   ports:
  #     - 8090:80
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: 1234
  #   container_name: PGAdmin42
