// import { PrismaClient } from '@prisma/client';
import prisma from '@/lib/prisma';
import { TodosGrid } from '@/todos';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Listado de Todo',
  description: 'Generated by create next app',
};

export default async function RestTodosPage() {
  const todos = await prisma.todo.findMany({ orderBy: { description: 'asc' } });

  return (
    <>
      <h1>Page Rest Todo</h1>
      <TodosGrid todos={todos} />
    </>
  );
}
