export const dynamic = 'force-dynamic';
export const revalidate = 0;

// import { PrismaClient } from '@prisma/client';
import prisma from '@/lib/prisma';
import { TodosGrid, TodosNew } from '@/todos';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Listado de Todo',
  description: 'Generated by create next app',
};

export default async function RestTodosPage() {
  const todos = await prisma.todo.findMany({ orderBy: { description: 'asc' } });

  return (
    <>
      <div className="w-full px-5 mx-5 mb-5">
        <TodosNew />
      </div>

      <TodosGrid todos={todos} />
    </>
  );
}
