export const dynamic = 'force-dynamic';
export const revalidate = 0;

import prisma from '@/lib/prisma';
import { TodosGrid, TodosNew } from '@/todos';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Listado de Todo',
  description: 'Generated by create next app',
};

export default async function ServeTodosPage() {
  const todos = await prisma.todo.findMany({ orderBy: { description: 'asc' } });
  console.log('construido');

  return (
    <>
      <span className="text-3xl mb-10">Server Actions</span>
      <div className="w-full px-5 mx-5 mb-5">
        <TodosNew />
      </div>

      <TodosGrid todos={todos} />
    </>
  );
}
